### ISSUE TITLE
References to websvn.info

### ISSUE THREAD

**Issue by xavierba** [websvnphp/websvnphp.github.io#5]
There are still a couple occurrences of links to the old and now squatted old websvn.info domain name:
- https://github.com/websvnphp/websvnphp.github.io/blob/a6eebe1aaa0769172bf314702849c42341a1cfd9/news.atom.xml#L3
- https://github.com/websvnphp/websvnphp.github.io/blob/a6eebe1aaa0769172bf314702849c42341a1cfd9/news.atom.xml#L8
- https://github.com/websvnphp/websvnphp.github.io/blob/2ee4072eadc12752236a87a199b07013b2f926fd/news/websvn-has-a-new-home.html#L9
- https://github.com/websvnphp/websvnphp.github.io/blob/2ee4072eadc12752236a87a199b07013b2f926fd/news/websvn-has-a-new-home.html#L53
- https://github.com/websvnphp/websvnphp.github.io/blob/2ee4072eadc12752236a87a199b07013b2f926fd/news/index.html#L105
- https://github.com/websvnphp/websvnphp.github.io/blob/2ee4072eadc12752236a87a199b07013b2f926fd/news/websvn-2-3-0-coming-soon.html#L53
- https://github.com/websvnphp/websvnphp.github.io/blob/d8a1e98668a286271432994d0ae8aaa93fcf0679/docs/install.html#L287

This probably needs to be fixed.

**Comment by ams-tschoening** [comment]
Fixed `news.atom.xml`, but leaving the old news as-is, because otherwise they would be wrong. Not sure what to do with `install.html`, there isn't any demo system available anymore or is there? Removing the sentence seems easiest right now, the instructions still somewhat work without it.
