### ISSUE TITLE
Suggestion for changes in the website

### ISSUE THREAD

**Issue by k10blogger** [websvnphp/websvnphp.github.io#7]
I suggest the following changes in the website content.

1 - Remove reference to tigris.org | Make an updated about page that takes in the history.(though not needed)
2 - Remove "News" and make it to "Releases" a single page entry capturing legacy and recent releases.
3 - Move Contribute Page Content to the Home page as it is now only two links to gihub project. After moving eliminate the Contribute section and page altogether.
4 - Remove the donwloads page and reference to non existing tigris as all that information will be in "Releases" page

![image](https://user-images.githubusercontent.com/4973182/92993827-72a73a80-f512-11ea-84ef-8e8042a3bbe2.png)

**Comment by michael-o** [comment]
Good idea! I wonder whether we need Releases at all?! I rather would move this to the GitHub releases tab to avoid duplicate work. WDYT?

**Comment by ams-tschoening** [comment]
Is somebody able to download releases formerly available on trigris.org? The download-page e.g. links the following:

http://websvn.tigris.org/files/documents/1380/49056/websvn-2.3.3.tar.gz

Doesn't work for me anymore, but I might have some internet related problems. If it doesn't work for you as well, simply linking to the GitHub-releases directly in the main menu seems sufficient for me as well.

**Comment by michael-o** [comment]
Tigris seems to be gone at all.

**Comment by k10blogger** [comment]
Tigris is completely gone last date was 1 july 2020.
